apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- toYaml .Values.server.labels | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.server.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}