apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- toYaml .Values.server.labels | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 8080
  selector:
    {{- range $key, $value := .Values.server.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}