name: helm-pr-check

on:
  push:
    branches:
      - master
      - main
      - '!gh-pages'
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches:
      - master
      - main
      - '!gh-pages'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check-docs-update:
    name: check-docs-update
    runs-on: ubuntu-latest
    container: jnorwood/helm-docs:v1.14.2
    steps:
      - name: Install git
        run: |
          apk add git
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check for changes
        run: |
          # fix fatal: detected dubious ownership in repository at
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          helm-docs
          if [ -z "$(git status --porcelain)" ]; then
            echo "Docs are up-to-date"
          else
            echo "Docs are stale. Run helm-docs . locally. The following files have been changed:"
            git diff
            exit 1
          fi

  lint:
    name: lint-charts
    runs-on: ubuntu-latest
    outputs:
      IS_CHANGED: ${{ steps.list-changed.outputs.IS_CHANGED }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.11.0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true

      - name: Run chart-testing (prepare)
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: |
          ct lint --target-branch ${{ github.event.repository.default_branch }} --config=ct.yaml
